### ISSUE TITLE
找不到百度地图的MAP对象

### ISSUE THREAD

**Issue by longye321** [China-ls/angular-baidu-maps#1]
已经按照当前例子里面讲的，设置了 ui-baidu-map="myMap"，但返回的对象是个undefined，应该和版本没什么关系吧，代码我也看了一下，也不是很复杂

**Comment by China-ls** [comment]
首先我解释下这个问题可能发生的情况：
  1、第一种情况，与demo.html中文件结构相同的时候，如果你使用$scope.myMap是null的情况，是由于地图未初始化完成，因为controller是会先一步初始化完成，所以安全的做法是在onMapLoaded方法被调用之后，再使用$scope.myMap对象
2、当你的界面结构比较复杂的时候，而此时你是通过data-ng-include进来的界面的情况下，你的地图引用可能是被绑定到了上一层Controller的$scope对象下

声明一下，这个并不需要你的$scope去声明myMap，指令会自动帮你创建这个属性，具体操作请看src/angularjs-baidu-maps.js文件中第55行里面是通过model.assign(scope, map);将当前的地图引用设置给$scope

具体$parse的用法，请参考 https://docs.angularjs.org/api/ng/service/$parse 
具体src中第55行功能，请参考文档$parse内容中右下角最后一行对assign 的解释
